title: "Foysal's Blog"
description: "A professional hacking and tech blog"
author: "Foysal"
baseurl: ""
url: "https://foysal1627.github.io"
timezone: Asia/Dhaka

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true 
  syntax_highlighter: rouge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock


plugins:
  - jekyll-paginate



