title: "Foysal's Blog"
description: "A professional hacking and tech blog"
author: "Foysal"
baseurl: ""
url: "https://foysal1627.github.io"
timezone: Asia/Dhaka

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination settings (যদি লিস্টে বেশি পোস্ট থাকে)
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
